# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/tux/Dev ++/Omicron"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/tux/Dev ++/Omicron"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/tux/Dev ++/Omicron/CMakeFiles" "/home/tux/Dev ++/Omicron/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/tux/Dev ++/Omicron/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named omicron

# Build rule for target.
omicron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 omicron
.PHONY : omicron

# fast build rule for target.
omicron/fast:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/build
.PHONY : omicron/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f deps/glfw/CMakeFiles/uninstall.dir/build.make deps/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f deps/glfw/src/CMakeFiles/glfw.dir/build.make deps/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/heightmap.dir/build.make deps/glfw/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/gears.dir/build.make deps/glfw/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/particles.dir/build.make deps/glfw/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/wave.dir/build.make deps/glfw/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/boing.dir/build.make deps/glfw/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/simple.dir/build.make deps/glfw/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) -f deps/glfw/examples/CMakeFiles/splitview.dir/build.make deps/glfw/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/windows.dir/build.make deps/glfw/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/sharing.dir/build.make deps/glfw/tests/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/title.dir/build.make deps/glfw/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/threads.dir/build.make deps/glfw/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/empty.dir/build.make deps/glfw/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/msaa.dir/build.make deps/glfw/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/tearing.dir/build.make deps/glfw/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/events.dir/build.make deps/glfw/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/gamma.dir/build.make deps/glfw/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/glfwinfo.dir/build.make deps/glfw/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/iconify.dir/build.make deps/glfw/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/monitors.dir/build.make deps/glfw/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/cursor.dir/build.make deps/glfw/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/joysticks.dir/build.make deps/glfw/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/clipboard.dir/build.make deps/glfw/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) -f deps/glfw/tests/CMakeFiles/reopen.dir/build.make deps/glfw/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

deps/glew/src/glew.o: deps/glew/src/glew.c.o

.PHONY : deps/glew/src/glew.o

# target to build an object file
deps/glew/src/glew.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/glew/src/glew.c.o
.PHONY : deps/glew/src/glew.c.o

deps/glew/src/glew.i: deps/glew/src/glew.c.i

.PHONY : deps/glew/src/glew.i

# target to preprocess a source file
deps/glew/src/glew.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/glew/src/glew.c.i
.PHONY : deps/glew/src/glew.c.i

deps/glew/src/glew.s: deps/glew/src/glew.c.s

.PHONY : deps/glew/src/glew.s

# target to generate assembly for a file
deps/glew/src/glew.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/glew/src/glew.c.s
.PHONY : deps/glew/src/glew.c.s

deps/lodepng/lodepng.o: deps/lodepng/lodepng.c.o

.PHONY : deps/lodepng/lodepng.o

# target to build an object file
deps/lodepng/lodepng.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/lodepng/lodepng.c.o
.PHONY : deps/lodepng/lodepng.c.o

deps/lodepng/lodepng.i: deps/lodepng/lodepng.c.i

.PHONY : deps/lodepng/lodepng.i

# target to preprocess a source file
deps/lodepng/lodepng.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/lodepng/lodepng.c.i
.PHONY : deps/lodepng/lodepng.c.i

deps/lodepng/lodepng.s: deps/lodepng/lodepng.c.s

.PHONY : deps/lodepng/lodepng.s

# target to generate assembly for a file
deps/lodepng/lodepng.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/lodepng/lodepng.c.s
.PHONY : deps/lodepng/lodepng.c.s

deps/noise/noise.o: deps/noise/noise.c.o

.PHONY : deps/noise/noise.o

# target to build an object file
deps/noise/noise.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/noise/noise.c.o
.PHONY : deps/noise/noise.c.o

deps/noise/noise.i: deps/noise/noise.c.i

.PHONY : deps/noise/noise.i

# target to preprocess a source file
deps/noise/noise.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/noise/noise.c.i
.PHONY : deps/noise/noise.c.i

deps/noise/noise.s: deps/noise/noise.c.s

.PHONY : deps/noise/noise.s

# target to generate assembly for a file
deps/noise/noise.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/noise/noise.c.s
.PHONY : deps/noise/noise.c.s

deps/sqlite/sqlite3.o: deps/sqlite/sqlite3.c.o

.PHONY : deps/sqlite/sqlite3.o

# target to build an object file
deps/sqlite/sqlite3.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/sqlite/sqlite3.c.o
.PHONY : deps/sqlite/sqlite3.c.o

deps/sqlite/sqlite3.i: deps/sqlite/sqlite3.c.i

.PHONY : deps/sqlite/sqlite3.i

# target to preprocess a source file
deps/sqlite/sqlite3.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/sqlite/sqlite3.c.i
.PHONY : deps/sqlite/sqlite3.c.i

deps/sqlite/sqlite3.s: deps/sqlite/sqlite3.c.s

.PHONY : deps/sqlite/sqlite3.s

# target to generate assembly for a file
deps/sqlite/sqlite3.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/sqlite/sqlite3.c.s
.PHONY : deps/sqlite/sqlite3.c.s

deps/tinycthread/tinycthread.o: deps/tinycthread/tinycthread.c.o

.PHONY : deps/tinycthread/tinycthread.o

# target to build an object file
deps/tinycthread/tinycthread.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/tinycthread/tinycthread.c.o
.PHONY : deps/tinycthread/tinycthread.c.o

deps/tinycthread/tinycthread.i: deps/tinycthread/tinycthread.c.i

.PHONY : deps/tinycthread/tinycthread.i

# target to preprocess a source file
deps/tinycthread/tinycthread.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/tinycthread/tinycthread.c.i
.PHONY : deps/tinycthread/tinycthread.c.i

deps/tinycthread/tinycthread.s: deps/tinycthread/tinycthread.c.s

.PHONY : deps/tinycthread/tinycthread.s

# target to generate assembly for a file
deps/tinycthread/tinycthread.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/deps/tinycthread/tinycthread.c.s
.PHONY : deps/tinycthread/tinycthread.c.s

src/auth.o: src/auth.c.o

.PHONY : src/auth.o

# target to build an object file
src/auth.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/auth.c.o
.PHONY : src/auth.c.o

src/auth.i: src/auth.c.i

.PHONY : src/auth.i

# target to preprocess a source file
src/auth.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/auth.c.i
.PHONY : src/auth.c.i

src/auth.s: src/auth.c.s

.PHONY : src/auth.s

# target to generate assembly for a file
src/auth.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/auth.c.s
.PHONY : src/auth.c.s

src/client.o: src/client.c.o

.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/client.c.s
.PHONY : src/client.c.s

src/cube.o: src/cube.c.o

.PHONY : src/cube.o

# target to build an object file
src/cube.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/cube.c.o
.PHONY : src/cube.c.o

src/cube.i: src/cube.c.i

.PHONY : src/cube.i

# target to preprocess a source file
src/cube.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/cube.c.i
.PHONY : src/cube.c.i

src/cube.s: src/cube.c.s

.PHONY : src/cube.s

# target to generate assembly for a file
src/cube.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/cube.c.s
.PHONY : src/cube.c.s

src/db.o: src/db.c.o

.PHONY : src/db.o

# target to build an object file
src/db.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/db.c.o
.PHONY : src/db.c.o

src/db.i: src/db.c.i

.PHONY : src/db.i

# target to preprocess a source file
src/db.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/db.c.i
.PHONY : src/db.c.i

src/db.s: src/db.c.s

.PHONY : src/db.s

# target to generate assembly for a file
src/db.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/db.c.s
.PHONY : src/db.c.s

src/inventory.o: src/inventory.c.o

.PHONY : src/inventory.o

# target to build an object file
src/inventory.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/inventory.c.o
.PHONY : src/inventory.c.o

src/inventory.i: src/inventory.c.i

.PHONY : src/inventory.i

# target to preprocess a source file
src/inventory.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/inventory.c.i
.PHONY : src/inventory.c.i

src/inventory.s: src/inventory.c.s

.PHONY : src/inventory.s

# target to generate assembly for a file
src/inventory.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/inventory.c.s
.PHONY : src/inventory.c.s

src/item.o: src/item.c.o

.PHONY : src/item.o

# target to build an object file
src/item.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/item.c.o
.PHONY : src/item.c.o

src/item.i: src/item.c.i

.PHONY : src/item.i

# target to preprocess a source file
src/item.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/item.c.i
.PHONY : src/item.c.i

src/item.s: src/item.c.s

.PHONY : src/item.s

# target to generate assembly for a file
src/item.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/item.c.s
.PHONY : src/item.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/main.c.s
.PHONY : src/main.c.s

src/map.o: src/map.c.o

.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/map.c.s
.PHONY : src/map.c.s

src/matrix.o: src/matrix.c.o

.PHONY : src/matrix.o

# target to build an object file
src/matrix.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/matrix.c.o
.PHONY : src/matrix.c.o

src/matrix.i: src/matrix.c.i

.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/matrix.c.i
.PHONY : src/matrix.c.i

src/matrix.s: src/matrix.c.s

.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/matrix.c.s
.PHONY : src/matrix.c.s

src/parser.o: src/parser.c.o

.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/rendering.o: src/rendering.c.o

.PHONY : src/rendering.o

# target to build an object file
src/rendering.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/rendering.c.o
.PHONY : src/rendering.c.o

src/rendering.i: src/rendering.c.i

.PHONY : src/rendering.i

# target to preprocess a source file
src/rendering.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/rendering.c.i
.PHONY : src/rendering.c.i

src/rendering.s: src/rendering.c.s

.PHONY : src/rendering.s

# target to generate assembly for a file
src/rendering.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/rendering.c.s
.PHONY : src/rendering.c.s

src/ring.o: src/ring.c.o

.PHONY : src/ring.o

# target to build an object file
src/ring.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/ring.c.o
.PHONY : src/ring.c.o

src/ring.i: src/ring.c.i

.PHONY : src/ring.i

# target to preprocess a source file
src/ring.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/ring.c.i
.PHONY : src/ring.c.i

src/ring.s: src/ring.c.s

.PHONY : src/ring.s

# target to generate assembly for a file
src/ring.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/ring.c.s
.PHONY : src/ring.c.s

src/sign.o: src/sign.c.o

.PHONY : src/sign.o

# target to build an object file
src/sign.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/sign.c.o
.PHONY : src/sign.c.o

src/sign.i: src/sign.c.i

.PHONY : src/sign.i

# target to preprocess a source file
src/sign.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/sign.c.i
.PHONY : src/sign.c.i

src/sign.s: src/sign.c.s

.PHONY : src/sign.s

# target to generate assembly for a file
src/sign.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/sign.c.s
.PHONY : src/sign.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/util.c.s
.PHONY : src/util.c.s

src/worldgen/base_terrain.o: src/worldgen/base_terrain.c.o

.PHONY : src/worldgen/base_terrain.o

# target to build an object file
src/worldgen/base_terrain.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/base_terrain.c.o
.PHONY : src/worldgen/base_terrain.c.o

src/worldgen/base_terrain.i: src/worldgen/base_terrain.c.i

.PHONY : src/worldgen/base_terrain.i

# target to preprocess a source file
src/worldgen/base_terrain.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/base_terrain.c.i
.PHONY : src/worldgen/base_terrain.c.i

src/worldgen/base_terrain.s: src/worldgen/base_terrain.c.s

.PHONY : src/worldgen/base_terrain.s

# target to generate assembly for a file
src/worldgen/base_terrain.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/base_terrain.c.s
.PHONY : src/worldgen/base_terrain.c.s

src/worldgen/biome_desert.o: src/worldgen/biome_desert.c.o

.PHONY : src/worldgen/biome_desert.o

# target to build an object file
src/worldgen/biome_desert.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_desert.c.o
.PHONY : src/worldgen/biome_desert.c.o

src/worldgen/biome_desert.i: src/worldgen/biome_desert.c.i

.PHONY : src/worldgen/biome_desert.i

# target to preprocess a source file
src/worldgen/biome_desert.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_desert.c.i
.PHONY : src/worldgen/biome_desert.c.i

src/worldgen/biome_desert.s: src/worldgen/biome_desert.c.s

.PHONY : src/worldgen/biome_desert.s

# target to generate assembly for a file
src/worldgen/biome_desert.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_desert.c.s
.PHONY : src/worldgen/biome_desert.c.s

src/worldgen/biome_mesa.o: src/worldgen/biome_mesa.c.o

.PHONY : src/worldgen/biome_mesa.o

# target to build an object file
src/worldgen/biome_mesa.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_mesa.c.o
.PHONY : src/worldgen/biome_mesa.c.o

src/worldgen/biome_mesa.i: src/worldgen/biome_mesa.c.i

.PHONY : src/worldgen/biome_mesa.i

# target to preprocess a source file
src/worldgen/biome_mesa.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_mesa.c.i
.PHONY : src/worldgen/biome_mesa.c.i

src/worldgen/biome_mesa.s: src/worldgen/biome_mesa.c.s

.PHONY : src/worldgen/biome_mesa.s

# target to generate assembly for a file
src/worldgen/biome_mesa.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_mesa.c.s
.PHONY : src/worldgen/biome_mesa.c.s

src/worldgen/biome_rainforest.o: src/worldgen/biome_rainforest.c.o

.PHONY : src/worldgen/biome_rainforest.o

# target to build an object file
src/worldgen/biome_rainforest.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_rainforest.c.o
.PHONY : src/worldgen/biome_rainforest.c.o

src/worldgen/biome_rainforest.i: src/worldgen/biome_rainforest.c.i

.PHONY : src/worldgen/biome_rainforest.i

# target to preprocess a source file
src/worldgen/biome_rainforest.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_rainforest.c.i
.PHONY : src/worldgen/biome_rainforest.c.i

src/worldgen/biome_rainforest.s: src/worldgen/biome_rainforest.c.s

.PHONY : src/worldgen/biome_rainforest.s

# target to generate assembly for a file
src/worldgen/biome_rainforest.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_rainforest.c.s
.PHONY : src/worldgen/biome_rainforest.c.s

src/worldgen/biome_taiga.o: src/worldgen/biome_taiga.c.o

.PHONY : src/worldgen/biome_taiga.o

# target to build an object file
src/worldgen/biome_taiga.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_taiga.c.o
.PHONY : src/worldgen/biome_taiga.c.o

src/worldgen/biome_taiga.i: src/worldgen/biome_taiga.c.i

.PHONY : src/worldgen/biome_taiga.i

# target to preprocess a source file
src/worldgen/biome_taiga.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_taiga.c.i
.PHONY : src/worldgen/biome_taiga.c.i

src/worldgen/biome_taiga.s: src/worldgen/biome_taiga.c.s

.PHONY : src/worldgen/biome_taiga.s

# target to generate assembly for a file
src/worldgen/biome_taiga.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_taiga.c.s
.PHONY : src/worldgen/biome_taiga.c.s

src/worldgen/biome_temperate.o: src/worldgen/biome_temperate.c.o

.PHONY : src/worldgen/biome_temperate.o

# target to build an object file
src/worldgen/biome_temperate.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_temperate.c.o
.PHONY : src/worldgen/biome_temperate.c.o

src/worldgen/biome_temperate.i: src/worldgen/biome_temperate.c.i

.PHONY : src/worldgen/biome_temperate.i

# target to preprocess a source file
src/worldgen/biome_temperate.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_temperate.c.i
.PHONY : src/worldgen/biome_temperate.c.i

src/worldgen/biome_temperate.s: src/worldgen/biome_temperate.c.s

.PHONY : src/worldgen/biome_temperate.s

# target to generate assembly for a file
src/worldgen/biome_temperate.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/biome_temperate.c.s
.PHONY : src/worldgen/biome_temperate.c.s

src/worldgen/world.o: src/worldgen/world.c.o

.PHONY : src/worldgen/world.o

# target to build an object file
src/worldgen/world.c.o:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/world.c.o
.PHONY : src/worldgen/world.c.o

src/worldgen/world.i: src/worldgen/world.c.i

.PHONY : src/worldgen/world.i

# target to preprocess a source file
src/worldgen/world.c.i:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/world.c.i
.PHONY : src/worldgen/world.c.i

src/worldgen/world.s: src/worldgen/world.c.s

.PHONY : src/worldgen/world.s

# target to generate assembly for a file
src/worldgen/world.c.s:
	$(MAKE) -f CMakeFiles/omicron.dir/build.make CMakeFiles/omicron.dir/src/worldgen/world.c.s
.PHONY : src/worldgen/world.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... omicron"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... heightmap"
	@echo "... gears"
	@echo "... particles"
	@echo "... wave"
	@echo "... boing"
	@echo "... simple"
	@echo "... splitview"
	@echo "... windows"
	@echo "... sharing"
	@echo "... title"
	@echo "... threads"
	@echo "... empty"
	@echo "... msaa"
	@echo "... tearing"
	@echo "... events"
	@echo "... gamma"
	@echo "... glfwinfo"
	@echo "... iconify"
	@echo "... monitors"
	@echo "... cursor"
	@echo "... joysticks"
	@echo "... clipboard"
	@echo "... reopen"
	@echo "... deps/glew/src/glew.o"
	@echo "... deps/glew/src/glew.i"
	@echo "... deps/glew/src/glew.s"
	@echo "... deps/lodepng/lodepng.o"
	@echo "... deps/lodepng/lodepng.i"
	@echo "... deps/lodepng/lodepng.s"
	@echo "... deps/noise/noise.o"
	@echo "... deps/noise/noise.i"
	@echo "... deps/noise/noise.s"
	@echo "... deps/sqlite/sqlite3.o"
	@echo "... deps/sqlite/sqlite3.i"
	@echo "... deps/sqlite/sqlite3.s"
	@echo "... deps/tinycthread/tinycthread.o"
	@echo "... deps/tinycthread/tinycthread.i"
	@echo "... deps/tinycthread/tinycthread.s"
	@echo "... src/auth.o"
	@echo "... src/auth.i"
	@echo "... src/auth.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/cube.o"
	@echo "... src/cube.i"
	@echo "... src/cube.s"
	@echo "... src/db.o"
	@echo "... src/db.i"
	@echo "... src/db.s"
	@echo "... src/inventory.o"
	@echo "... src/inventory.i"
	@echo "... src/inventory.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/rendering.o"
	@echo "... src/rendering.i"
	@echo "... src/rendering.s"
	@echo "... src/ring.o"
	@echo "... src/ring.i"
	@echo "... src/ring.s"
	@echo "... src/sign.o"
	@echo "... src/sign.i"
	@echo "... src/sign.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/worldgen/base_terrain.o"
	@echo "... src/worldgen/base_terrain.i"
	@echo "... src/worldgen/base_terrain.s"
	@echo "... src/worldgen/biome_desert.o"
	@echo "... src/worldgen/biome_desert.i"
	@echo "... src/worldgen/biome_desert.s"
	@echo "... src/worldgen/biome_mesa.o"
	@echo "... src/worldgen/biome_mesa.i"
	@echo "... src/worldgen/biome_mesa.s"
	@echo "... src/worldgen/biome_rainforest.o"
	@echo "... src/worldgen/biome_rainforest.i"
	@echo "... src/worldgen/biome_rainforest.s"
	@echo "... src/worldgen/biome_taiga.o"
	@echo "... src/worldgen/biome_taiga.i"
	@echo "... src/worldgen/biome_taiga.s"
	@echo "... src/worldgen/biome_temperate.o"
	@echo "... src/worldgen/biome_temperate.i"
	@echo "... src/worldgen/biome_temperate.s"
	@echo "... src/worldgen/world.o"
	@echo "... src/worldgen/world.i"
	@echo "... src/worldgen/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

